### ISSUE TITLE
RuntimeError when training: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by maybeluo** [yuanzhoulvpi2017/zero_nlp#5]
Error when running:
`pythonsimple_thu_chatglm6b/train_chatglm6b.py`

Traceback (most recent call last):
  File "train_chatglm6b.py", line 111, in <module>
    trainer.train()
  File "/home/project/zero_nlp/simple_thu_chatglm6b/MyTrainer.py", line 1634, in train
    return inner_training_loop(
  File "/home/project/zero_nlp/simple_thu_chatglm6b/MyTrainer.py", line 1901, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/project/zero_nlp/simple_thu_chatglm6b/MyTrainer.py", line 2655, in training_step
    self.scaler.scale(loss).backward()
  File "/home/miniconda3/envs/chatglm/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/miniconda3/envs/chatglm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: GET was unable to find an engine to execute this computation

my envs:
- python=3.8.16
- torch=2.0.0
- nvidia 3090 with cuda version 11.5

**Comment by maybeluo** [comment]
I downgrade torch to 1.13, but encounter `torch.cuda.OutOfMemoryError: CUDA out of memory`instead when running.

**Comment by yuanzhoulvpi2017** [comment]
我这边cuda：11.6；torch：1.13.显存刚刚好

![image](https://user-images.githubusercontent.com/30610553/227057232-f7319027-8075-468e-a276-543fa15a07c1.png)

**Comment by illuz** [comment]
我也遇到了这个问题，降级后解决了，分享下我的执行步骤：

python 3.10.10，cuda 11.7
新建 conda 环境后执行 https://pytorch.org/get-started/previous-versions/#v1130 安装旧版本的 torch：
`conda install pytorch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 pytorch-cuda=11.7 -c pytorch -c nvidia`
然后 `pip install protobuf==3.20.0 transformers icetk cpm_kernels peft datasets`
