### ISSUE TITLE
报错: RuntimeError: Internal: [MASK] is already defined.

### ISSUE THREAD

**Issue by EssentialCuber** [yuanzhoulvpi2017/zero_nlp#61]
**正常按照ipynb的流程操作，报错如下**
机器学习方面的小白，请教下是什么问题，该如何解决，谢谢大神。
```
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\TrainProject\chatglm6b\train_chatglm6b.py", line 19, in <module>
    tokenizer = AutoTokenizer.from_pretrained("thuglm", trust_remote_code=True)
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 679, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1958, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\thuglm\tokenization_chatglm.py", line 214, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\thuglm\tokenization_chatglm.py", line 35, in __init__
    self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\thuglm\tokenization_chatglm.py", line 68, in _build_text_tokenizer
    self._configure_tokenizer(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\thuglm\tokenization_chatglm.py", line 64, in _configure_tokenizer
    text_tokenizer.refresh()
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\icetk\text_tokenizer.py", line 31, in refresh
    self.sp.Load(model_proto=self.proto.SerializeToString())
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\sentencepiece\__init__.py", line 904, in Load
    return self.LoadFromSerializedProto(model_proto)
  File "C:\Users\Administrator\PycharmProjects\TrainProject\venv\lib\site-packages\sentencepiece\__init__.py", line 250, in LoadFromSerializedProto
    return _sentencepiece.SentencePieceProcessor_LoadFromSerializedProto(self, serialized)
RuntimeError: Internal: [MASK] is already defined.
```

**Comment by Switchsyj** [comment]
将所有的150000， 150001替换成self.config.mask_token_id， self.config.gmask_token_id。这里150000明显和tokenizer的MASK id对应不上。我的模型文件来自”THUDM/chatglm-6b“，但是现在我还没有完全解决，又遇到了新的bug:
```python
=======mask id: 130000, 130001======
{'input_ids': tensor([[ 67193,  65093,  76131,  63826,  71661,  64328,  68253,  64042,     31,
         130000, 130004]], device='cuda:0'), 'attention_mask': tensor([[[[False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
            True],
          [False, False, False, False, False, False, False, False, False, False,
           False]]]], device='cuda:0'), 'position_ids': tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], device='cuda:0'), 'max_length': 500, 'num_beams': 1, 'do_sample': True, 'top_p': 0.7, 'temperature': 0.95, 'eos_token_id': 130005}
=======mask id: 130000, 130001======
Tensors must have same number of dimensions: got 4 and 2
```

**Comment by whitesay** [comment]
> 

你好 请问你解决这个问题了吗？我也遇到了一样的问题，谢谢！

**Comment by EssentialCuber** [comment]
> > 
> 
> 你好 请问你解决这个问题了吗？我也遇到了一样的问题，谢谢！

是cuda版本问题，修改为正确的版本就好了。

**Comment by Switchsyj** [comment]
我是直接使用的huggingface-chatglm6b的历史版本（下载下来load）
https://huggingface.co/THUDM/chatglm-6b/tree/42095d42ff56b81ff5647dec51cf31045b6eccb5
也解决了问题。
