### ISSUE TITLE
使用lora 微调后，调用生成报错 RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by chenyiwan** [yuanzhoulvpi2017/zero_nlp#62]
File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 1146, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 1171, in generate
    output_ids = super().generate(**kwargs)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/thudm/.local/lib/python3.7/site-packages/transformers/generation/utils.py", line 1462, in generate
    **model_kwargs,
  File "/home/thudm/.local/lib/python3.7/site-packages/transformers/generation/utils.py", line 2472, in sample
    output_hidden_states=output_hidden_states,
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 1080, in forward
    return_dict=return_dict,
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 922, in forward
    output_attentions=output_attentions
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 581, in forward
    output_attentions=output_attentions
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.cache/huggingface/modules/transformers_modules/chatglm-6b-finetuning/modeling_chatglm.py", line 283, in forward
    mixed_raw_layer = self.query_key_value.to(device=hidden_states.device)(hidden_states)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.local/lib/python3.7/site-packages/peft/tuners/lora.py", line 456, in forward
    after_A = self.lora_A(self.lora_dropout(x))
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float

请作者看看这是怎么回事呢。我微调时使用了fp16

加了model.eval() 后，又报这样的错了

Traceback (most recent call last):
  File "chat_server.py", line 83, in <module>
    model.eval()
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1930, in eval
    return self.train(False)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  File "/home/thudm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  [Previous line repeated 4 more times]
  File "/home/thudm/.local/lib/python3.7/site-packages/peft/tuners/lora.py", line 420, in train
    groups=sum(self.enable_lora),
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 8, 1, 1], but got 3-dimensional input of size [1, 16, 4096] instead

**Comment by chenyiwan** [comment]
已经解决

**Comment by yuanzhoulvpi2017** [comment]
加个`with torch.autocast("cuda"):`
