### ISSUE TITLE
Chatglm6b_ModelParallel_ptuning 编译错误

### ISSUE THREAD

**Issue by online2311** [yuanzhoulvpi2017/zero_nlp#73]
错误提示：
bash train_parallel.sh 
```
[INFO|modeling_utils.py:3034] 2023-04-13 05:24:33,465 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3036] 2023-04-13 05:24:33,466 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ./chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2692] 2023-04-13 05:24:33,515 >> Generation config file not found, using a generation config created from the model config.
input_ids [5, 65421, 61, 67329, 32, 98339, 61, 72043, 32, 65347, 61, 70872, 32, 69768, 61, 68944, 32, 67329, 64103, 61, 96914, 150001, 150004, 5, 87052, 96914, 81471, 64562, 65759, 64493, 64988, 6, 65840, 65388, 74531, 63825, 75786, 64009, 63823, 65626, 63882, 64619, 65388, 6, 64480, 65604, 85646, 110945, 10, 64089, 65966, 87052, 67329, 65544, 6, 71964, 70533, 64417, 63862, 89978, 63991, 63823, 77284, 88473, 64219, 63848, 112012, 6, 71231, 65099, 71252, 66800, 85768, 64566, 64338, 100323, 75469, 63823, 117317, 64218, 64257, 64051, 74197, 6, 63893, 150005, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
Traceback (most recent call last):
  File "/home/nodecloud/Chatglm6b_ModelParallel_ptuning/main_parallel.py", line 450, in <module>
    main()
  File "/home/nodecloud/Chatglm6b_ModelParallel_ptuning/main_parallel.py", line 277, in main
    print_dataset_example(train_dataset[0])
  File "/home/nodecloud/Chatglm6b_ModelParallel_ptuning/main_parallel.py", line 257, in print_dataset_example
    print("inputs", tokenizer.decode(example["input_ids"]))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.conda/envs/train/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3476, in decode
    return self._decode(
           ^^^^^^^^^^^^^
  File "/home/nodecloud/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 268, in _decode
    return self.sp_tokenizer.decode(token_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 117, in decode
    text = self._get_text_tokenizer().decode(ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 29, in decode
    return self.sp.DecodeIds(ids)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.conda/envs/train/lib/python3.11/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.conda/envs/train/lib/python3.11/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodecloud/.conda/envs/train/lib/python3.11/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Out of range: piece id is out of range.
```

**Comment by online2311** [comment]
采用官方 ``https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning `` 项目可以正常训练。 
我想使用``Chatglm6b_ModelParallel_ptuning`` 多卡训练的能力。
